### ISSUE TITLE
QuestionDisplay component

### ISSUE THREAD

**Issue by cheehongw** [CS3219-AY2324S1/ay2324s1-course-assessment-g10#7]
# Intro

We need a frontend component that is able to render the questions to the end user. 

The envisioned usage of this component would be for it to render the coding question for the end user to read and see. Possibly like 
leetcode where the question is displayed to the side and the code editor takes up the other side. Bonus points if the component can be dynamically resized to allow more space for the code editor.

# Rendering of question data

The component would need to consume question data for it to render the question. Some of the sample questions provided in `CS3219Assignments.pdf` contain text and images and also some markdown syntax, so hopefully the component can render them in markdown as well.

![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g10/assets/72195240/8097c8cc-56d3-4ec2-906d-e771ab2cb05e)
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g10/assets/72195240/55027d9a-46cb-44f2-919b-486cb9398cdc)

The backend question service should provide this question data to the component as and when it is needed. As for the format of the question data, it could be returned as a raw string in markdown syntax. 

Thoughts?

**Comment by Eclipse-Dominator** [comment]
Resolved by #23
