### ISSUE TITLE
Code editor component

### ISSUE THREAD

**Issue by cheehongw** [CS3219-AY2324S1/ay2324s1-course-assessment-g10#9]
# Intro

We will need a frontend component that serves as the code editor for the end user. Some of the features of this code editor (in order of importance):

- basic text editor with a monospace font
- showing cursor of the user
- labeling the cursor with the user's name (like gdocs or vscode collab feature)
- syntax highlighting (nice to have, but can be tricky when there are multiple people working on the same code)
- component can be dynamically resized
- showing multiple cursor positions when multiple users work on it
- concurrency & conflict management

**Comment by Eclipse-Dominator** [comment]
Resolved by #42
